version: '3'
services:
  dtupay:
    image: dtupay
    container_name: dtupay
    ports:
     - "8042:8080"

  TokenMicroService:
    image: tokenmicroservice
    container_name: tokenmicroservice

  AccountMicroService:
    image: accountmicroservice
    container_name: accountmicroservice

  rabbitMq:
    image: rabbitmq:management
    container_name: rabbitMq_container
#    ports:
#      - "8041:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER="aholdet"
#      - RABBITMQ_DEFAULT_PASS="01982cb258ec11ebae930242ac130002"