version: '3'
services:    
  dtupay:
    image: dtupay
    container_name: dtupay
    ports:
     - "8042:8080"

  RabbitMQTest:
    image: rabbittest
    container_name: rabbittest
    depends_on:
     - "rabbitMq"
    # command: ["./wait-for-it.sh","rabbitmq:5672","java", "-Xmx64m", "-jar", "rabbitmqtest-1.0.0.jar"]

  TokenMicroService:
    image: tokenmicroservice
    container_name: tokenmicroservice
    depends_on:
      - "rabbitMq"
    ports:
      - "8043:8080"

  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container


  # rabbitMq:
  #   image: rabbitmq:management
  #   container_name: rabbitMq_container
  #   ports:
  #    - "8080:15672"

  # Nginx:
  #   image: nginx:latest
  #   container_name: nginx_reverseProxy
  #   volumes: 
  #    - ./nginx.conf:/etc/nginx/conf.d/default.conf     
  #   ports:
  #    - "8042:8080"