version: '3'
services:    
  dtupay:
    image: dtupay
    container_name: dtupay    
    ports:
     - "8042:8080"

  RabbitMQService:
    image: rabbitmqservice
    container_name: rabbitmqservice
    depends_on:
     - "rabbitMq"
    command: ["./wait-for-it.sh","rabbitmq:5672","java", "-Xmx64m", "-jar", "rabbitmqservice-1.0.0.jar"]

  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container