version: '3'
services:    
  dtupay:
    image: dtupay
    container_name: dtupay    
    ports:
     - "8042:8080"

  service1:
    image: service1
    container_name: service1
    depends_on:
     - "rabbitMq"
    command: ["./wait-for-it.sh","rabbitmq:5672","java", "-Xmx64m", "-jar", "service1-1.0.0.jar"]

  rabbitMq:
    image: rabbitmq
    container_name: rabbitMq_container